stages:
  - compile
  - deploy_goodmedicine
  - deploy_b2b

compile:
 stage: compile
 script:
   - mvn clean install -U  deploy  -Dmaven.test.skip=true -f ./pom.xml
   - rm -rf /app/project/"$PROJECT_NAME"
   - mkdir -p /app/project/"$PROJECT_NAME"
   - cp -rf ./target/lib /app/project/"$PROJECT_NAME"/
   - cp -rf ./target/"$PROJECT_NAME".jar /app/project/"$PROJECT_NAME"/

deploy_goodmedicine:
 stage: deploy_goodmedicine
 script:
   - python /app/script/deploy_goodmedicine_serviceapp.py "$PROJECT_NAME"

deploy_b2b:
 stage: deploy_b2b
 script:
   - python /app/script/deploy_b2b_serviceapp.py "$PROJECT_NAME"